## PyTorch exercises

### Tensors

1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]
5. Perform a matrix multiplication of two tensors of size (2, 4) and (4, 2). Then do it in-place.
6. Do element-wise multiplication of two randomly filled $(n_1,n_2,n_3)$ tensors. Then store the result in an Numpy array.

### Forward-prop/backward-prop
1. Create a Tensor that `requires_grad` of size (5, 5).
2. Sum the values in the Tensor.
3. Multiply the tensor by 2 and assign the result to a new python variable (i.e. `x = result`)
4. Sum the variable's elements and assign to a new python variable
5. Print the gradients of all the variables
6. Now perform a backward pass on the last variable (NOTE: for each new python variable that you define, call `.retain_grad()`)
7. Print all gradients again

### Tensors

#### 1. Make a tensor of size (2, 17)

In [ ]:
# Завдання 1.1
# Створіть тензор розміру (2, 17) за допомогою PyTorch
import torch  # Імпорт бібліотеки PyTorch

# Створення тензора розміру (2, 17)
tensor_2_17 = torch.empty(2, 17)  # Ініціалізація порожнього тензора розміру (2, 17)
print(tensor_2_17)  # Виведення тензора

tensor([[-3.9636e+28,  1.5008e-42,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])


#### 2. Make a torch.FloatTensor of size (3, 1)

In [ ]:
# Завдання 1.2
# Створіть тензор розміру 3x1 з випадковими числами
float_tensor_3_1 = torch.FloatTensor(3, 1)  # Ініціалізація FloatTensor розміру (3, 1)
print(float_tensor_3_1)  # Виведення тензора

#### 3. Make a torch.LongTensor of size (5, 2, 1) - fill the entire tensor with 7s

In [ ]:
# Завдання 1.3
# Створіть тензор розміру 5x2x1 з випадковими числами
long_tensor_5_2_1 = torch.LongTensor(5, 2, 1)  # Створення LongTensor розміру (5, 2, 1)
long_tensor_5_2_1.fill_(7)  # Заповнення всіх елементів тензора значенням 7
print(long_tensor_5_2_1)  # Виведення тензора

tensor([[[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]]])


#### 4. Make a torch.ByteTensor of size (5,) - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [ ]:
# Завдання 1.4
# Створення ByteTensor розміру (5,) з певними значеннями
byte_tensor_5 = torch.ByteTensor([0, 1, 1, 1, 0])  # Ініціалізація тензора зі значеннями
print(byte_tensor_5)  # Виведення тензора


#### 5. Perform a matrix multiplication of two tensors of size (2, 4) and (4, 2). Then do it in-place.

In [ ]:
import torch
# Завдання 1.5
# Визначення тензорів розміру (2, 4) та (4, 2)
tensor_2_4 = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]], dtype=torch.float32)  # Створення тензора розміру (2, 4)
tensor_4_2 = torch.tensor([[1, 2], [3, 4], [5, 6], [7, 8]], dtype=torch.float32)  # Створення тензора розміру (4, 2)

# Виконання матричного множення
result = torch.mm(tensor_2_4, tensor_4_2)  # Множення тензорів

# Виконання операції на місці
result.copy_(torch.mm(tensor_2_4, tensor_4_2))  # Копіювання результату множення в той самий тензор

# Виведення результату
print(result)  # Друк результату

tensor([[ 50.,  60.],
        [114., 140.]])


### 6. Do element-wise multiplication of two randomly filled $(n_1,n_2,n_3)$ tensors. Then store the result in an Numpy array.

In [ ]:
# Завдання 1.6

import torch
import numpy as np

# Визначення розмірів тензорів
n1, n2, n3 = 3, 4, 5  # Приклад розмірностей

# Створення двох тензорів розміру (n1, n2, n3) з випадковими значеннями
tensor1 = torch.rand((n1, n2, n3))
tensor2 = torch.rand((n1, n2, n3))

# Виконання поелементного множення
result_tensor = tensor1 * tensor2

# Конвертація результату в масив NumPy
result_numpy = result_tensor.numpy()

# Виведення результату
print("Результат у вигляді масиву NumPy:")
print(result_numpy)

Result as a NumPy array:
[[[8.0913201e-02 1.0251788e-01 4.3824100e-01 5.9520698e-04 4.7455318e-02]
  [1.0721257e-02 4.7187068e-02 2.5632126e-02 6.8205014e-02 2.0582740e-01]
  [6.4126164e-01 7.8127629e-01 1.5373982e-01 1.9002731e-01 1.0586552e-01]
  [1.4671938e-01 8.5626316e-01 5.1371229e-01 3.2080803e-02 1.2666081e-01]]

 [[5.1400334e-02 7.1172053e-03 1.6671610e-01 4.8011041e-01 4.0605437e-02]
  [1.8661666e-01 1.5510209e-01 6.0405135e-02 1.3629410e-01 2.8612775e-01]
  [6.3583261e-01 2.7981967e-01 4.9747080e-01 2.5507939e-01 4.3247148e-02]
  [6.7940086e-01 2.9854285e-02 2.7045611e-01 1.1803163e-01 8.6608611e-02]]

 [[7.8264207e-01 4.4808713e-01 2.1134344e-01 6.2085688e-03 1.9311391e-01]
  [8.5135972e-01 3.2269815e-01 9.9327393e-02 2.4349305e-01 3.4213719e-01]
  [1.3887273e-01 4.6312865e-02 7.7444196e-01 1.5767957e-01 6.9257146e-01]
  [7.1053278e-01 4.9949777e-01 3.0032876e-01 9.9873757e-03 5.5796381e-02]]]


### Forward-prop/backward-prop

#### 1. Create a Tensor that `requires_grad` of size (5, 5).

In [10]:
# Завдання 2.1
import torch

# Створення тензора розміру (5, 5) з requires_grad=True
tensor = torch.randn(5, 5, requires_grad=True)  # Ініціалізація тензора з випадковими значеннями

# Виведення тензора
print("Tensor with requires_grad=True:")
print(tensor)  # Виведення значень тензора

Tensor with requires_grad=True:
tensor([[-0.0797,  2.5414, -0.6879, -0.2701, -1.0695],
        [ 0.1065,  0.8646,  0.8761, -1.4088,  0.2975],
        [-1.4083,  1.7995,  0.5939,  0.7281,  1.7296],
        [-1.1887, -0.5628,  0.7342, -1.2208,  1.2898],
        [ 0.6215,  0.6599,  1.1842, -0.5666, -0.2329]], requires_grad=True)


#### 2. Sum the values in the Tensor.


In [ ]:
# Завдання 2.2
# Підсумовування значень у тензорі
tensor_sum = torch.sum(tensor)  # Обчислення суми всіх елементів тензора
print("Сума значень тензора:", tensor_sum)  # Виведення суми значень тензора

Сума значень тензора: tensor(5.3308, grad_fn=<SumBackward0>)


#### 3. Multiply the tensor by 2 and assign the result to a new python variable (i.e. `x = result`)

In [ ]:
# Завдання 2.3
# Помножте тензор на 2 та призначте результат новій змінній
x = tensor * 2  # Операція множення тензора на 2
print("Результат множення тензора на 2:") 
print(x)  # Виведення значень нового тензора

Результат множення тензора на 2:
tensor([[-0.1595,  5.0828, -1.3758, -0.5402, -2.1389],
        [ 0.2130,  1.7291,  1.7522, -2.8177,  0.5950],
        [-2.8166,  3.5991,  1.1879,  1.4561,  3.4593],
        [-2.3773, -1.1257,  1.4685, -2.4415,  2.5797],
        [ 1.2429,  1.3199,  2.3683, -1.1332, -0.4659]], grad_fn=<MulBackward0>)


#### 4. Sum the variable's elements and assign to a new python variable

In [ ]:
# Завдання 2.4
x_sum = torch.sum(x)  # Обчислення суми всіх елементів змінної x
print("Сума значень змінної x:", x_sum)  # Виведення суми значень

Сума значень змінної x: tensor(10.6615, grad_fn=<SumBackward0>)


#### 5. Print the gradients of all the variables

In [21]:
# Завдання 2.5
import torch

# Створення тензора з requires_grad=True
tensor = torch.randn(5, 5, requires_grad=True)

# Сума значень у тензорі
tensor_sum = tensor.sum()

# Множення тензора на 2
x = tensor * 2

# Сума елементів змінної x
x_sum = x.sum()

# Виконання зворотного проходу
x_sum.backward()

# Виведення градієнтів
print("Градієнт тензора (tensor):")
print(tensor.grad)  # Градієнт для tensor

print("Градієнт x:")  # Градієнт для x не буде доступний
print(x.grad)  # Це поверне None, оскільки retain_grad() не використовується


Градієнт тензора (tensor):
tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]])
Градієнт x:
None


C:\Users\kleot\AppData\Local\Temp\ipykernel_8996\3560284378.py:24: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\build\aten\src\ATen/core/TensorBody.h:494.)
  print(x.grad)  # Це поверне None, оскільки retain_grad() не використовується


#### 6. Now perform a backward pass on the last variable (NOTE: for each new python variable that you define, call `.retain_grad()`)

In [19]:
import torch

# 1. Створення тензора з requires_grad=True
tensor = torch.randn(5, 5, requires_grad=True)

# 2. Сума значень у тензорі
tensor_sum = tensor.sum()

# 3. Множення тензора на 2
x = tensor * 2
x.retain_grad()  # Збереження градієнтів для змінної x

# 4. Сума елементів змінної x
x_sum = x.sum()
x_sum.retain_grad()  # Збереження градієнтів для змінної x_sum

# 6. Виконання зворотного проходу
x_sum.backward()

# 7. Виведення градієнтів
print("Градієнт тензора (tensor):")
print(tensor.grad)  # Градієнт для tensor

print("Градієнт x:")
print(x.grad)  # Градієнт для x

print("Градієнт x_sum:")
print(x_sum.grad)  # Градієнт для x_sum

Градієнт тензора (tensor):
tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]])
Градієнт x:
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
Градієнт x_sum:
tensor(1.)


#### 7. Print all gradients again

In [20]:
# Printing gradients of tensor
print("Gradient of tensor:")
print(tensor.grad)

# Printing gradients of x
print("Gradient of x:")
print(x.grad)

# Printing gradients of x_sum
print("Gradient of x_sum:")
print(x_sum.grad)

Gradient of tensor:
tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]])
Gradient of x:
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
Gradient of x_sum:
tensor(1.)


### Deep-forward NNs
1. Look at Lab 3. In Exercise 12 there, you had to build an $L$-layer neural network with the following structure: *[LINEAR -> RELU]$\times$(L-1) -> LINEAR -> SIGMOID*. Reimplement the manual code in PyTorch.
2. Compare test accuracy using different optimizers: SGD, Adam, Momentum.

#### Look at Lab 3. In Exercise 12 there, you had to build an $L$-layer neural network with the following structure: *[LINEAR -> RELU]$\times$(L-1) -> LINEAR -> SIGMOID*. Reimplement the manual code in PyTorch.

### From Lab 3

In [ ]:
# def L_layer_model(X, Y, layers_dims, learning_rate = 0.0075, num_iterations = 3000, print_cost=False):
#     """
#     Implements a L-layer neural network: [LINEAR->RELU]*(L-1)->LINEAR->SIGMOID.
    
#     Arguments:
#     X -- input data, of shape (n_x, number of examples)
#     Y -- true "label" vector (containing 1 if cat, 0 if non-cat), of shape (1, number of examples)
#     layers_dims -- list containing the input size and each layer size, of length (number of layers + 1).
#     learning_rate -- learning rate of the gradient descent update rule
#     num_iterations -- number of iterations of the optimization loop
#     print_cost -- if True, it prints the cost every 100 steps
    
#     Returns:
#     parameters -- parameters learnt by the model. They can then be used to predict.
#     """

#     np.random.seed(1)
#     costs = []                         # keep track of cost
    
#     # Parameters initialization.
#     #(≈ 1 line of code)
#     # parameters = ...
#     # CODE_START
#     parameters = initialize_parameters_deep(layers_dims)
#     # CODE_END
    
#     # Loop (gradient descent)
#     for i in range(0, num_iterations):

#         # Forward propagation: [LINEAR -> RELU]*(L-1) -> LINEAR -> SIGMOID.
#         #(≈ 1 line of code)
#         # AL, caches = ...
#         # CODE_START
#         AL, caches = L_model_forward(X, parameters)
#         # CODE_END
        
#         # Compute cost.
#         #(≈ 1 line of code)
#         # cost = ...
#         # CODE_START
#         cost = compute_cost(AL, Y)
#         # CODE_END
    
#         # Backward propagation.
#         #(≈ 1 line of code)
#         # grads = ...    
#         # CODE_START
#         grads = L_model_backward(AL, Y, caches)
#         # CODE_END
 
#         # Update parameters.
#         #(≈ 1 line of code)
#         # parameters = ...
#         # CODE_START
#         parameters = update_parameters(parameters, grads, learning_rate)
#         # CODE_END
                
#         # Print the cost every 100 iterations
#         if print_cost and i % 100 == 0 or i == num_iterations - 1:
#             print("Cost after iteration {}: {}".format(i, np.squeeze(cost)))
#         if i % 100 == 0 or i == num_iterations:
#             costs.append(cost)
    
#     return parameters, costs

In [ ]:
# Завдання 3.1

import torch
import torch.nn as nn
import torch.nn.functional as F

class LLayerNeuralNetwork(nn.Module):
    def __init__(self, layers_dims):
        """
        Ініціалізація багатошарової нейронної мережі.
        
        Аргументи:
        layers_dims -- список, що містить розміри вхідного шару та кожного шару мережі, довжина (кількість шарів + 1).
        """
        super(LLayerNeuralNetwork, self).__init__()
        self.layers = nn.ModuleList()  # Створення списку для зберігання шарів
        
        # Створення шарів: [LINEAR -> RELU]*(L-1) -> LINEAR -> SIGMOID
        for i in range(len(layers_dims) - 1):
            self.layers.append(nn.Linear(layers_dims[i], layers_dims[i + 1]))  # Додавання лінійного шару
        
    def forward(self, X):
        """
        Прямий прохід для багатошарової нейронної мережі.
        
        Аргументи:
        X -- вхідні дані, форма (n_x, кількість прикладів)
        
        Повертає:
        AL -- вихід останнього шару (прогнози)
        """
        A = X  # Ініціалізація вхідних даних
        for i in range(len(self.layers) - 1):
            A = F.relu(self.layers[i](A))  # Застосування LINEAR -> RELU для (L-1) шарів
        AL = torch.sigmoid(self.layers[-1](A))  # Застосування LINEAR -> SIGMOID для останнього шару
        return AL  # Повернення результату

# Визначення функції навчання
def train_model(model, X, Y, learning_rate=0.0075, num_iterations=3000, print_cost=False):
    """
    Навчання багатошарової нейронної мережі.
    
    Аргументи:
    model -- модель PyTorch
    X -- вхідні дані, форма (кількість прикладів, n_x)
    Y -- істинний вектор "міток", форма (кількість прикладів, 1)
    learning_rate -- швидкість навчання для правила оновлення градієнтного спуску
    num_iterations -- кількість ітерацій циклу оптимізації
    print_cost -- якщо True, виводить вартість кожні 100 кроків
    
    Повертає:
    model -- навчена модель PyTorch
    costs -- список вартостей під час навчання
    """
    optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)  # Оптимізатор SGD
    criterion = nn.BCELoss()  # Функція втрат: бінарна крос-ентропія
    costs = []  # Список для зберігання вартостей
    
    for i in range(num_iterations):
        # Прямий прохід
        AL = model(X)  # Обчислення прогнозів
        
        # Обчислення вартості
        cost = criterion(AL, Y)  # Обчислення втрат
        
        # Зворотний прохід
        optimizer.zero_grad()  # Обнулення градієнтів
        cost.backward()  # Обчислення градієнтів
        
        # Оновлення параметрів
        optimizer.step()  # Оновлення ваг
        
        # Виведення та збереження вартості
        if print_cost and (i % 100 == 0 or i == num_iterations - 1):
            print(f"Вартість після ітерації {i}: {cost.item()}")  # Виведення вартості
        if i % 100 == 0 or i == num_iterations - 1:
            costs.append(cost.item())  # Додавання вартості до списку
    
    return model, costs  # Повернення навченої моделі та списку вартостей

# Приклад використання
if __name__ == "__main__":
    # Визначення розмірів шарів
    layers_dims = [5, 4, 3, 1]  # Приклад: 4-шарова мережа (вхід: 5, приховані: 4 -> 3, вихід: 1)
    
    # Створення моделі
    model = LLayerNeuralNetwork(layers_dims)  # Ініціалізація моделі
    
    # Генерація випадкових даних для навчання
    X = torch.randn(100, layers_dims[0])  # 100 прикладів, розмір входу = 5
    Y = torch.randint(0, 2, (100, 1)).float()  # Бінарні мітки (0 або 1)
    
    # Навчання моделі
    trained_model, costs = train_model(model, X, Y, learning_rate=0.0075, num_iterations=1000, print_cost=True)  # Навчання моделі

Вартість після ітерації 0: 0.7123847007751465
Вартість після ітерації 100: 0.7054418325424194
Вартість після ітерації 200: 0.7014930248260498
Вартість після ітерації 300: 0.699198842048645
Вартість після ітерації 400: 0.6978076100349426
Вартість після ітерації 500: 0.6969026923179626
Вартість після ітерації 600: 0.6962734460830688
Вартість після ітерації 700: 0.6957966685295105
Вартість після ітерації 800: 0.6954225301742554
Вартість після ітерації 900: 0.6950730085372925
Вартість після ітерації 999: 0.6947607398033142


### Compare test accuracy using different optimizers: SGD, Adam, Momentum.

In [ ]:
# Завдання 3.2

import torch  # Імпорт бібліотеки PyTorch
import torch.nn as nn  # Імпорт модуля для створення нейронних мереж
import torch.nn.functional as F  # Імпорт функціоналу для активаційних функцій
from torch.utils.data import DataLoader, TensorDataset  # Імпорт для роботи з даними
import numpy as np  # Імпорт бібліотеки NumPy

# Визначення багатошарової нейронної мережі
class LLayerNeuralNetwork(nn.Module):
    def __init__(self, layers_dims):  # Ініціалізація класу
        super(LLayerNeuralNetwork, self).__init__()  # Виклик конструктора базового класу
        self.layers = nn.ModuleList()  # Створення списку для зберігання шарів
        for i in range(len(layers_dims) - 1):  # Цикл для створення шарів
            self.layers.append(nn.Linear(layers_dims[i], layers_dims[i + 1]))  # Додавання лінійного шару
        
    def forward(self, X):  # Прямий прохід
        A = X  # Ініціалізація вхідних даних
        for i in range(len(self.layers) - 1):  # Цикл для (L-1) шарів
            A = F.relu(self.layers[i](A))  # Застосування LINEAR -> RELU
        AL = torch.sigmoid(self.layers[-1](A))  # Застосування LINEAR -> SIGMOID для останнього шару
        return AL  # Повернення результату

# Функція навчання з вибором оптимізатора
def train_model(model, X_train, Y_train, X_test, Y_test, optimizer_type="SGD", learning_rate=0.0075, num_iterations=3000, print_cost=False):
    criterion = nn.BCELoss()  # Функція втрат: бінарна крос-ентропія
    if optimizer_type == "SGD":  # Вибір оптимізатора SGD
        optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
    elif optimizer_type == "Momentum":  # Вибір оптимізатора з моментумом
        optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate, momentum=0.9)
    elif optimizer_type == "Adam":  # Вибір оптимізатора Adam
        optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
    else:  # Помилка для невідомого типу оптимізатора
        raise ValueError("Unsupported optimizer type. Choose from 'SGD', 'Momentum', or 'Adam'.")
    
    costs = []  # Список для зберігання вартостей
    for i in range(num_iterations):  # Цикл навчання
        AL = model(X_train)  # Прямий прохід
        cost = criterion(AL, Y_train)  # Обчислення втрат
        
        optimizer.zero_grad()  # Обнулення градієнтів
        cost.backward()  # Зворотний прохід
        optimizer.step()  # Оновлення параметрів
        
        if print_cost and (i % 100 == 0 or i == num_iterations - 1):  # Виведення вартості
            print(f"Cost after iteration {i}: {cost.item()}")
        if i % 100 == 0 or i == num_iterations - 1:  # Збереження вартості
            costs.append(cost.item())
    
    with torch.no_grad():  # Оцінка точності на тестових даних
        AL_test = model(X_test)  # Прогнозування
        predictions = (AL_test > 0.5).float()  # Перетворення на бінарні значення
        accuracy = (predictions == Y_test).float().mean().item()  # Обчислення точності
        print(f"Test Accuracy with {optimizer_type}: {accuracy * 100:.2f}%")
    
    return accuracy  # Повернення точності

# Приклад використання
if __name__ == "__main__":
    layers_dims = [5, 4, 3, 1]  # Визначення розмірів шарів
    for optimizer_type in ["SGD", "Momentum", "Adam"]:  # Порівняння оптимізаторів
        print(f"\nTraining with {optimizer_type} optimizer:")
        model = LLayerNeuralNetwork(layers_dims)  # Ініціалізація моделі
        train_model(model, X_train, Y_train, X_test, Y_test, optimizer_type=optimizer_type, learning_rate=0.0075, num_iterations=1000, print_cost=True)  # Навчання моделі



Training with SGD optimizer:
Cost after iteration 0: 0.6998189687728882
Cost after iteration 100: 0.697780430316925
Cost after iteration 200: 0.6962934136390686
Cost after iteration 300: 0.6952027678489685
Cost after iteration 400: 0.6943681240081787
Cost after iteration 500: 0.6937806010246277
Cost after iteration 600: 0.6933227777481079
Cost after iteration 700: 0.692910373210907
Cost after iteration 800: 0.6925489902496338
Cost after iteration 900: 0.6922160387039185
Cost after iteration 999: 0.6918961405754089
Test Accuracy with SGD: 50.00%

Training with Momentum optimizer:
Cost after iteration 0: 0.7661643028259277
Cost after iteration 100: 0.6926202178001404
Cost after iteration 200: 0.6919843554496765
Cost after iteration 300: 0.6912888884544373
Cost after iteration 400: 0.6902697086334229
Cost after iteration 500: 0.6886981129646301
Cost after iteration 600: 0.6858437061309814
Cost after iteration 700: 0.6813675165176392
Cost after iteration 800: 0.6733954548835754
Cost after